# On part de l'image officielle PyTorch
FROM pytorch/pytorch:latest

# On définit le dossier de travail par défaut
WORKDIR /workspace/code

# (Optionnel) Si vous avez besoin d'autres paquets Python, vous pouvez les ajouter ici
# RUN pip install pandas matplotlib scikit-learn